org.gradle.parallel=true
org.gradle.warning.mode=all

java_version=25

#########################################################
# Minecraft Versions                                    #
#########################################################
minecraft_version=26.1-snapshot-3
minecraft_version_range=[26.1-snapshot-3]
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.0.0-alpha.7+snapshot-3
neoforge_version_range=[26.1.0.0-alpha,)

#########################################################
# Third party dependencies
#########################################################
snakeyaml_version=1.33
directory_watcher_version=0.17.1
junit_version=5.13.4
flatbuffers_version=23.5.26
ffmpeg_version=6.0-1.5.9
assertj_version=3.26.0
lucene_version=10.3.2
