modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/AppliedEnergistics/GuideME/issues"
displayURL = "https://github.com/AppliedEnergistics/GuideME/"
logoFile = "logo.png"
authors = "shartte"
license = "See GitHub repository for details"

[[mods]]
modId = "guideme"
version = "0.0.0"
displayName = "GuideME"
description = ""

[[dependencies.guideme]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "${neoforge_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.guideme]]
modId = "minecraft"
type = "REQUIRED"
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"
