package guideme.web;

import com.sun.net.httpserver.SimpleFileServer;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.nio.file.Files;
import java.nio.file.Path;
import org.jetbrains.annotations.ApiStatus;

/**
 * Serves a website generated by {@link WebSiteGenerator} locally over HTTP on a random port, to preview it in a
 * browser. Opening the pages directly from disk does not work, since browsers block the scripts used by the website.
 * <p>
 * Takes the website folder as its only argument and runs until it is stopped.
 */
@ApiStatus.Experimental
public final class WebSiteServer {
    private WebSiteServer() {
    }

    public static void main(String[] args) {
        if (args.length != 1) {
            System.err.println("Usage: <website-folder>");
            System.exit(1);
        }

        var root = Path.of(args[0]).toAbsolutePath().normalize();
        if (!Files.isDirectory(root)) {
            System.err.println("Website folder " + root + " does not exist.");
            System.exit(1);
        }

        // Only listen locally, on a random free port
        var server = SimpleFileServer.createFileServer(
                new InetSocketAddress(InetAddress.getLoopbackAddress(), 0),
                root,
                SimpleFileServer.OutputLevel.INFO);
        server.start();

        System.out.println("Serving " + root + " at http://localhost:" + server.getAddress().getPort() + "/");
        System.out.println("Press Ctrl+C to stop.");
    }
}
