package guideme.internal.web;

import guideme.internal.siteexport.model.IndexModel;
import guideme.web.html.HtmlFragment;
import guideme.web.html.HtmlNode;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import org.jspecify.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Generates a website with multiple versions of a guide, i.e. one for each Minecraft version a mod supports.
 * <p>
 * Each version is generated by {@link WebSiteGenerator} into a folder named after its Minecraft version (the major
 * version if the export has one). The root of the website lists all versions and links to the sitemaps of all versions.
 */
public final class VersionedWebSiteGenerator {
    private static final Logger LOG = LoggerFactory.getLogger(VersionedWebSiteGenerator.class);

    /**
     * Compares the numeric parts of versions, so that 1.20.10 is newer than 1.20.9.
     */
    private static final Comparator<String> VERSION_ORDER = (a, b) -> {
        var aParts = a.split("\\D+");
        var bParts = b.split("\\D+");
        for (int i = 0; i < Math.max(aParts.length, bParts.length); i++) {
            var diff = Long.compare(parsePart(aParts, i), parsePart(bParts, i));
            if (diff != 0) {
                return diff;
            }
        }
        return a.compareTo(b);
    };

    /**
     * @param site           The options for the whole website. The data folder contains a folder with an export for
     *                       each version. The change version URL defaults to the root of the website.
     * @param developmentUrl URL of a separately published development version of the guide to link to.
     */
    public record Options(WebSiteGenerator.Options site, @Nullable String developmentUrl) {
    }

    /**
     * A guide version found in the data folder.
     *
     * @param path       The folder of the version below the root of the website, i.e. {@code 1.21.1}.
     * @param dataFolder The folder containing the export of the version.
     */
    record Version(String path, Path dataFolder, IndexModel index) {
    }

    private final Options options;
    private final WebSiteGenerator.Options site;

    public VersionedWebSiteGenerator(Options options) {
        this.options = options;
        this.site = options.site();
    }

    public void generate() {
        var versions = findVersions();
        if (versions.isEmpty()) {
            throw new IllegalArgumentException("Found no guide exports in the folders of " + site.dataFolder());
        }

        try {
            if (site.clean()) {
                WebSiteGenerator.cleanOutputFolder(site);
            }

            for (var version : versions) {
                LOG.info("Generating guide version {} from {}", version.path(), version.dataFolder());
                var versionOutputFolder = site.outputFolder().resolve(version.path());
                new WebSiteGenerator(new WebSiteGenerator.Options(
                        version.dataFolder(),
                        versionOutputFolder,
                        site.webAssetsPath(),
                        site.changeVersionUrl() != null ? site.changeVersionUrl() : site.basePath(),
                        site.title(),
                        site.logo(),
                        site.favicon(),
                        site.siteUrl(),
                        site.basePath() + version.path() + "/",
                        site.pageSubdirectories(),
                        false,
                        site.stylesheets(),
                        site.scripts())).generate();
                // Crawlers only look for robots.txt at the root of the website
                Files.deleteIfExists(versionOutputFolder.resolve("robots.txt"));
            }

            writeRootPages(versions);
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to generate the website in " + site.outputFolder(), e);
        }
    }

    /**
     * {@return all versions in the data folder, newest first}
     */
    List<Version> findVersions() {
        var versions = new ArrayList<Version>();
        var versionsByPath = new HashMap<String, Path>();
        try (var folders = Files.list(site.dataFolder())) {
            for (var folder : folders.sorted().toList()) {
                if (!Files.isRegularFile(folder.resolve("index.json"))) {
                    continue;
                }
                var index = GuideExportReader.readIndex(folder);
                var path = index.gameMajorVersion() != null ? index.gameMajorVersion() : index.gameVersion();
                var otherFolder = versionsByPath.put(path, folder);
                if (otherFolder != null) {
                    throw new IllegalArgumentException("The exports in " + otherFolder + " and " + folder
                            + " are both for Minecraft " + path);
                }
                versions.add(new Version(path, folder, index));
            }
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to list the guide exports in " + site.dataFolder(), e);
        }
        versions.sort(Comparator.comparing(Version::path, VERSION_ORDER.reversed()));
        return versions;
    }

    private void writeRootPages(List<Version> versions) throws IOException {
        var webAssetsBundle = new WebAssetsBundle(site);
        webAssetsBundle.copyToOutputFolder();
        var resourceCopier = new WebResourceCopier(site.outputFolder());
        WebSiteGenerator.addBranding(site, webAssetsBundle, resourceCopier);
        WebSiteGenerator.addSiteResources(site, webAssetsBundle, resourceCopier);

        // The 404 page can be served from any URL, so all pages at the root use absolute links
        var urlPrefix = site.basePath();

        var index = new HtmlFragment();
        index.append(versionList(versions, urlPrefix));
        if (options.developmentUrl() != null) {
            index.append(HtmlNode.tag("p")
                    .setClassName("development-version")
                    .append("Looking for unreleased changes? See the ")
                    .append(HtmlNode.tag("a").setAttribute("href", options.developmentUrl())
                            .append("development version"))
                    .append("."));
        }
        writeFile("index.html", webAssetsBundle.realizeVersionsTemplate(site.title(), urlPrefix,
                "Choose a Minecraft Version", site.title(), index, site.absoluteUrl("")));

        var notFound = new HtmlFragment();
        notFound.append(HtmlNode.tag("p").append(
                "The page you are looking for does not exist. Choose the guide for your Minecraft version:"));
        notFound.append(versionList(versions, urlPrefix));
        writeFile("404.html", webAssetsBundle.realizeVersionsTemplate(site.title(), urlPrefix,
                "Page Not Found", "Page Not Found - " + site.title(), notFound, null));

        writeSitemapIndex(versions);
    }

    private static HtmlNode versionList(List<Version> versions, String urlPrefix) {
        var list = HtmlNode.tag("ul").setClassName("version-list");
        for (int i = 0; i < versions.size(); i++) {
            var version = versions.get(i);
            var link = HtmlNode.tag("a")
                    .setAttribute("href", urlPrefix + version.path() + "/")
                    .append(HtmlNode.tag("span").setClassName("version-name")
                            .append("Minecraft " + version.path()));
            if (i == 0) {
                link.append(HtmlNode.tag("span").setClassName("version-badge").append("Latest"));
            }
            link.append(HtmlNode.tag("span").setClassName("version-date")
                    .append("Updated " + formatDate(version.index().generated())));
            list.append(HtmlNode.tag("li").append(link));
        }
        return list;
    }

    /**
     * Writes a sitemap.xml that points to the sitemaps of all versions, and a robots.txt that points to it, if the URL
     * of the website is known.
     */
    private void writeSitemapIndex(List<Version> versions) throws IOException {
        if (site.siteUrl() == null) {
            return;
        }

        var sitemap = new StringBuilder();
        sitemap.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        sitemap.append("<sitemapindex xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n");
        for (var version : versions) {
            sitemap.append("  <sitemap><loc>")
                    .append(HtmlNode.escapeHtml(site.absoluteUrl(version.path() + "/sitemap.xml")))
                    .append("</loc><lastmod>").append(formatDate(version.index().generated()))
                    .append("</lastmod></sitemap>\n");
        }
        sitemap.append("</sitemapindex>\n");
        writeFile("sitemap.xml", sitemap.toString());

        writeFile("robots.txt", "User-agent: *\nAllow: /\n\nSitemap: " + site.absoluteUrl("sitemap.xml") + "\n");
    }

    private void writeFile(String path, String content) throws IOException {
        Files.writeString(site.outputFolder().resolve(path), content, StandardCharsets.UTF_8);
    }

    private static String formatDate(long timestamp) {
        return DateTimeFormatter.ISO_LOCAL_DATE.format(Instant.ofEpochMilli(timestamp).atOffset(ZoneOffset.UTC));
    }

    private static long parsePart(String[] parts, int i) {
        if (i >= parts.length || parts[i].isEmpty()) {
            return 0;
        }
        try {
            return Long.parseLong(parts[i]);
        } catch (NumberFormatException e) {
            return 0;
        }
    }
}
