package guideme.siteexport.web;

import guideme.internal.web.StaticSiteServer;
import org.jetbrains.annotations.ApiStatus;

/**
 * Serves a website generated by {@link WebSiteGenerator} locally over HTTP on a random port, to preview it in a
 * browser. Opening the pages directly from disk does not work, since browsers block the scripts used by the website.
 * <p>
 * Takes the website folder as its only argument and runs until it is stopped.
 */
@ApiStatus.Experimental
public final class WebSiteServer {
    private WebSiteServer() {
    }

    public static void main(String[] args) {
        StaticSiteServer.main(args);
    }
}
