modLoader = "javafml"
loaderVersion = "*"
logoFile = "logo.png"
authors = "shartte"
license = "See GitHub repository for details"

[[mods]]
modId = "guideme"
version = "${version}"
displayName = "GuideME"
description = "GuideME offers the foundation for your mods or modpacks guidebook."
issueTrackerURL = "https://github.com/AppliedEnergistics/GuideME/issues"
displayURL = "https://github.com/AppliedEnergistics/GuideME/"

[[dependencies.guideme]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.guideme]]
modId = "minecraft"
type = "REQUIRED"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
